### ISSUE TITLE
Mulig å få til/endre funksjoner til å?:

### ISSUE THREAD

**Issue by RobertBMar** [DenEkteTruls/opencv-to-tkinter-API#1]
Mulig å få til/endre funksjoner til å?:
Bare registrere pixel-offset fra midt når man klikker på et punkt, ikke hele tiden, og sende disse x,y-verdiene til eksample programmet, slik at de kan kunne være med i kalkulasjoner der. Denne fuksjonen trengs bare på høyre bilde

Kunne velge cv2. ROI på høyre bilde når knapp blir trykket. Intet rektangel eller lignende skal tegnes etterpå, bare muligheten til å få verdiene fra den (typ. (10, 10, 20, 20)) til eksample programmet

ps. ingen ting som haster i det hele tatt, trenger ikke gjøre det heller :)

**Comment by caspernag** [comment]
Det skal jeg gjøre vettu. Ferdig til i kveld.

**Comment by RobertBMar** [comment]
Nice mann!
